version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    networks:
      - backend

  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - laravel
    networks:
      - backend

  laravel:
    container_name: laravel
    tty: true
    build:
      context: ./laravel
    # ports:
    #     - '8000:80'
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
    networks:
      - backend

  nextjs:
    build: ./nextjs
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
        - ./nextjs:/usr/src/app
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend: