version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend
  laravel:
    container_name: laravel
    build:
      context: ./laravel
    ports:
        - '8080:80'
    volumes:
      - ./laravel:/var/www/laravel
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
    networks:
      - backend
  nextjs:
    build: ./nextjs
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
        - ./nextjs:/usr/src/app
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend: